spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
        instance-id: consul-one
  application:
    name: consul-one
server:
  port: 8501